4Soft-de/kbl-model

kbl24/pom.xml, kbl24/src/main/java/com/foursoft/kblmodel/kbl24/KblReader.java, kbl24/src/main/java/com/foursoft/kblmodel/kbl24/KblWriter.java, kbl24/src/test/java/com/foursoft/kblmodel/kbl24/BasicLoadingTest.java, kbl24/src/test/java/com/foursoft/kblmodel/kbl24/BasicWritingTest.java, pom.xml
- [ x] I have checked for similar PRs.
- [ x] I have read the [contributing guidelines](https://github.com/4Soft-de/kbl-model/blob/develop/.github/CONTRIBUTING.md).
- [x ] Code
- [ x] Documentation
Closes:-
uses the new jaxb-enhanced-navigation V 1.0.2 lib (must be done before releasing this)
=> New kbl reader writer

README.md, kbl24/src/examples/java/MyKblReader.java, kbl24/src/examples/java/MyKblWriter.java, kbl24/src/main/java/com/foursoft/kblmodel/kbl24/KblWriter.java
Closes: -
- kbl thread local writer
- simpler documentation/examples
=> clean up api, easier examples

.github/workflows/maven.yml, pom.xml
General description goes here.
=> chore: added sonar analysis to workflow.

pom.xml
General description goes here.
=> chore: bump version navigation-extender

.github/CONTRIBUTING.md, README.md
Updates the contribution guidelines to include two new information.
=> Update Contributor Guidelines

.github/workflows/maven.yml, .github/workflows/release.yml, kbl24-assertions/pom.xml, kbl24/pom.xml, pom.xml
Updated the java version of the build to Java 11.0.2.
In addition, JAXB dependencies have been adjusted since JAXB has been removed from JDK.
=> Update Java Version for GH Actions

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Adds a new GitHub issue template targeting feature requests. Also when creating an issue from any template, representative labels will be added to it after its creation now.
=> Feature Request Template with default Labels

.github/dependabot.yml
Adds DependaBot to keep Maven and GH Action dependencies up2date.
=> Add DependaBot

pom.xml
=> fix: update jaxb2-basics to correct version

kbl24/src/main/java/com/foursoft/kblmodel/kbl24/HasAliasId.java, kbl24/src/main/java/com/foursoft/kblmodel/kbl24/HasDescription.java, kbl24/src/main/java/com/foursoft/kblmodel/kbl24/HasIdentification.java, kbl24/src/main/java/com/foursoft/kblmodel/kbl24/HasInstallationInformation.java, kbl24/src/main/java/com/foursoft/kblmodel/kbl24/HasPart.java, kbl24/src/main/java/com/foursoft/kblmodel/kbl24/HasPlacement.java, kbl24/src/main/java/com/foursoft/kblmodel/kbl24/HasProcessingInformation.java, kbl24/src/main/java/com/foursoft/kblmodel/kbl24/HasReferenceElement.java, kbl24/src/main/resources/kbl24/KBL24_SR1-ext.xjb
=> Added multiple capability interfaces for generic handling (#41)

kbl24/src/main/java/com/foursoft/kblmodel/kbl24/SchemaFactory.java, kbl24/src/test/java/com/foursoft/kblmodel/kbl24/SchemaFactoryTest.java
Added SchemaFactory for KBL 2.4 to create schema objects.
=> added SchemaFactory

README.md, kbl24/src/examples/java/MyKblReader.java, kbl24/src/examples/java/MyKblWriter.java, kbl24/src/test/java/com/foursoft/kblmodel/kbl24/BasicLoadingTest.java, kbl24/src/test/java/com/foursoft/kblmodel/kbl24/BasicWritingTest.java, kbl24/src/test/resources/sample.kbl
I noticed there were a few things wrong with the ReadMe, for example the KBL elements not having id attributes when they should or the assertion example using tabs instead of spaces.
I fixed all of that and adjusted the test cases.
=> Fix errors in the ReadMe and adjust Tests regarding this 

v24/src/main/java/module-info.java
- Added missing package export
=> Added missing package export

pom.xml, v24/pom.xml, v24/src/main/java/module-info.java
=> Removed unnecessary modules

v24/src/main/java/com/foursoft/harness/kbl/v24/visitor/FunctionVisitor.java, v24/src/test/java/com/foursoft/harness/kbl/v24/visitor/FunctionVisitorTest.java
=> added FunctionVisitor

v24/src/main/java/com/foursoft/harness/kbl/v24/exception/KblException.java, v24/src/main/java/com/foursoft/harness/kbl/v24/validation/KblValidation.java, v24/src/main/java/com/foursoft/harness/kbl/v24/validation/SchemaFactory.java, v24/src/main/java/module-info.java, v24/src/test/java/com/foursoft/harness/kbl/v24/validation/KblValidationTest.java
added KblValidation and KblException
=> added KblValidation and KblException

v24/src/main/java/com/foursoft/harness/kbl/v24/HasInstallationInformation.java, v24/src/main/java/com/foursoft/harness/kbl/v24/HasInstruction.java, v24/src/main/java/com/foursoft/harness/kbl/v24/HasProcessingInformation.java, v24/src/main/java/com/foursoft/harness/kbl/v24/util/StreamUtils.java, v24/src/main/java/module-info.java, v24/src/main/resources/kbl24/KBL24_SR1-ext.xjb, v24/src/test/java/com/foursoft/harness/kbl/v24/HasInstallationInformationTest.java, v24/src/test/java/com/foursoft/harness/kbl/v24/HasProcessingInformationTest.java
Extend HasProcessingInformation and HasInstallationInformation interfaces to filter Instruction
=> Extend HasProcessingInformation and HasInstallationInformation

v24/src/main/java/com/foursoft/harness/kbl/v24/HasConnectionOrOccurrences.java, v24/src/main/java/com/foursoft/harness/kbl/v24/HasRelatedAssembly.java, v24/src/main/java/com/foursoft/harness/kbl/v24/util/StreamUtils.java, v24/src/main/resources/kbl24/KBL24_SR1-ext.xjb
Added new interfaces HasConnectionOrOccurrences and HasRelatedAssembly
=> Added new interfaces HasConnectionOrOccurrences and HasRelatedAssembly

v24/src/main/resources/kbl24/generate-xjb-from-kbl-model.xsl
General description goes here.
=> Added XSL to generate XJB files from UML Model

v24/src/main/java/com/foursoft/harness/kbl/v24/HasRelatedOccurrence.java, v24/src/main/resources/kbl24/KBL24_SR1-ext.xjb, v25/src/main/java/com/foursoft/harness/kbl/v25/HasRelatedOccurrence.java, v25/src/main/resources/kbl25/KBL25_SR1-ext.xjb
Added new interface HasRelatedOccurrence
=> Added new interface HasRelatedOccurrence

v24/src/main/java/com/foursoft/harness/kbl/v24/HasSpecifiedOccurrences.java, v25/src/main/java/com/foursoft/harness/kbl/v25/HasSpecifiedOccurrences.java
Added new interface HasSpecifiedOccurrences
=> Added new interface HasSpecifiedOccurrences

v24/src/main/java/com/foursoft/harness/kbl/v24/HasParentAssemblyPart.java, v24/src/main/resources/kbl24/KBL24_SR1-ext.xjb, v25/src/main/java/com/foursoft/harness/kbl/v25/HasParentAssemblyPart.java, v25/src/main/java/com/foursoft/harness/kbl/v25/HasRelatedOccurrence.java, v25/src/main/resources/kbl25/KBL25_SR1-ext.xjb
Added new interface HasParentAssemblyPart
=> Added new interface HasParentAssemblyPart

v24/src/main/java/com/foursoft/harness/kbl/v24/HasRelatedOccurrence.java, v25/src/main/java/com/foursoft/harness/kbl/v25/HasRelatedOccurrence.java
Fixed generic types at HasRelatedOccurrence #87
=> Fixed generic types at HasRelatedOccurrence

v24/src/main/java/com/foursoft/harness/kbl/v24/HasWireNumber.java, v24/src/main/resources/kbl24/KBL24_SR1-ext.xjb, v25/src/main/java/com/foursoft/harness/kbl/v25/HasWireNumber.java, v25/src/main/resources/kbl25/KBL25_SR1-ext.xjb
Added new interface HasWireNumber
=> Added new interface HasWireNumber
